### ISSUE TITLE
Talon hangs when trying to remove quote

### ISSUE THREAD

**Issue by jboga** [quentez/talonjs#4]
Message id: 215480654
Quotations.js L176
Talon hangs indefinitely when trying to match line 26 of message with the following pattern: 
/(-_[>]?[ ]?(Op|Am)[ ]._(._\n){0,2}._(schreef|verzond|geschreven|schrieb)[ ]_._:)/

Use MessageResource.fetchWithContent to reproduce.

**Comment by quentez** [comment]
This should be fixed in 1a88bc584c6c3df6b0e33e59887b3f34f4d7c1fd
